const products = [
 {id:'steam',name:'Compte Steam',image:'steam.jpg',category:'gaming',description:'Pour les « juste une dernière partie ».',variants:[['Sélection découverte',1900],['Sélection aventure',3400]]},
 {id:'steam-gift',name:'Carte cadeau Steam',image:'steam-gift.jpg',category:'gaming',description:'Le plaisir de choisir son prochain jeu.',variants:[['Crédit découverte · exemple',2400],['Crédit supérieur · exemple',4600]]},
 {id:'xbox',name:'Xbox Game Pass',image:'xbox.jpg',category:'gaming',description:'Une nouvelle aventure à chaque envie.',variants:[['PC · 1 mois',1900],['Ultimate · 1 mois',2900]]},
 {id:'netflix',name:'Netflix',image:'netflix.jpg',category:'streaming',description:'Pour les soirées qui se prolongent.',variants:[['1 mois',1200],['3 mois',3300]]},
 {id:'spotify',name:'Spotify Premium',image:'spotify.jpg',category:'streaming',description:'La bande-son des petits moments.',variants:[['1 mois',700],['3 mois',1900]]},
 {id:'exitlag',name:'ExitLag',image:'exitlag.jpg',category:'gaming',description:'Un outil pour vos sessions en ligne.',variants:[['1 mois',1100],['3 mois',2900]]}
];
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('fr-DZ').format(n)+' DZD';
const plus='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M12 5v14"/></svg>';
let feature=0,filter='all',cart=[],motion=null,toastTimer;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function renderDeck(){
 const positions=['pos-minus-two','pos-minus-one','pos-center','pos-plus-one','pos-plus-two'];
 $('#deck').innerHTML=positions.map((position,i)=>{const index=(feature+i-2+products.length)%products.length,p=products[index];return `<button class="deck-card ${position}" data-feature="${index}" aria-label="Voir ${p.name}" aria-pressed="${index===feature}"><img src="../assets/products/${p.image}" alt="${p.name}"></button>`}).join('');
 const p=products[feature];$('#feature-title').textContent=p.name;$('#feature-description').textContent=p.description;$('#feature-price').textContent='Dès '+money(p.variants[0][1]);$('#feature-add').setAttribute('aria-label','Ajouter '+p.name+' au panier');
 $('#deck-dots').innerHTML=products.map((p,i)=>`<button data-feature="${i}" class="${i===feature?'active':''}" aria-label="Voir ${p.name}" aria-pressed="${i===feature}"></button>`).join('');
 if(motion&&!reduced)motion.animate('.feature-detail',{opacity:[.4,1],y:[8,0]},{duration:.35});
}
function changeFeature(index){feature=(index+products.length)%products.length;renderDeck()}
$('#previous').addEventListener('click',()=>changeFeature(feature-1));$('#next').addEventListener('click',()=>changeFeature(feature+1));
for(const target of ['#deck','#deck-dots'])$(target).addEventListener('click',e=>{const b=e.target.closest('[data-feature]');if(b){changeFeature(Number(b.dataset.feature));$(target).querySelector(`[data-feature="${feature}"]`)?.focus({preventScroll:true})}});
function renderCatalog(){const query=$('#search').value.trim().toLocaleLowerCase('fr');const found=products.filter(p=>(filter==='all'||p.category===filter)&&p.name.toLocaleLowerCase('fr').includes(query));$('#catalog').innerHTML=found.map(p=>`<article class="product" data-product="${p.id}"><div class="product-art"><img src="../assets/products/${p.image}" alt="${p.name}" loading="lazy"></div><div class="product-copy"><h3>${p.name}</h3><p>${p.description}</p><label class="variant">Votre formule<select data-variant="${p.id}">${p.variants.map((v,i)=>`<option value="${i}">${v[0]}</option>`).join('')}</select></label><div class="buy-line"><strong class="price">${money(p.variants[0][1])}</strong><button class="add-product" data-add="${p.id}" aria-label="Ajouter ${p.name} au panier">${plus}</button></div></div></article>`).join('');$('#no-results').hidden=found.length>0}
$('#search').addEventListener('input',renderCatalog);document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});renderCatalog()}));
$('#catalog').addEventListener('change',e=>{const id=e.target.dataset.variant;if(!id)return;const p=products.find(p=>p.id===id);e.target.closest('.product').querySelector('.price').textContent=money(p.variants[Number(e.target.value)][1])});
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2500)}
function add(id,variant){const item=cart.find(x=>x.id===id&&x.variant===variant);if(item)item.quantity++;else cart.push({id,variant,quantity:1});renderCart();toast(products.find(p=>p.id===id).name+' ajouté au panier')}
$('#catalog').addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(b)add(b.dataset.add,Number(b.closest('.product').querySelector('select').value))});$('#feature-add').addEventListener('click',()=>add(products[feature].id,0));
function renderCart(){const count=cart.reduce((n,x)=>n+x.quantity,0),total=cart.reduce((n,x)=>n+products.find(p=>p.id===x.id).variants[x.variant][1]*x.quantity,0);$('#header-count').textContent=count;$('#tray-summary').textContent=count?`${count} petit${count>1?'s':''} plaisir${count>1?'s':''}`:'Votre panier de petits plaisirs';$('#total').textContent=money(total);$('#checkout-button').disabled=!count;$('#checkout').hidden=true;$('#payment-result').textContent='';$('#cart-items').innerHTML=cart.length?cart.map((x,i)=>{const p=products.find(p=>p.id===x.id),v=p.variants[x.variant];return `<article class="cart-item"><img src="../assets/products/${p.image}" alt=""><div><h3>${p.name}</h3><p>${v[0]} · Quantité ${x.quantity}</p></div><strong>${money(v[1]*x.quantity)}</strong><button data-remove="${i}" aria-label="Retirer ${p.name}">Retirer</button></article>`}).join(''):'<p class="cart-empty">Votre panier est vide. Choisissez un petit plaisir pour commencer.</p>'}
function toggleCart(open=!$('#order-panel').hidden){$('#order-panel').hidden=open;document.querySelectorAll('[data-toggle-cart]').forEach(b=>b.setAttribute('aria-expanded',!open));if(!open)$('#order-title').focus({preventScroll:true})}
let opener;document.querySelectorAll('[data-toggle-cart]').forEach(b=>b.addEventListener('click',()=>{opener=b;toggleCart()}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#order-panel').hidden){toggleCart(true);opener?.focus({preventScroll:true})}});
$('#cart-items').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){cart.splice(Number(b.dataset.remove),1);renderCart();$('#order-title').focus({preventScroll:true})}});
$('#checkout-button').addEventListener('click',()=>{opener=$('#checkout-button');toggleCart(false);$('#checkout').hidden=false;$('#checkout input').focus();$('#checkout').scrollIntoView({block:'nearest',behavior:reduced?'instant':'smooth'})});
document.querySelectorAll('[name=payment]').forEach(input=>input.addEventListener('change',()=>{$('#payment-detail').textContent=input.value==='manual'?'Un transfert CCP / BaridiMob nécessiterait un justificatif et une validation manuelle. Ce circuit est séparé de Chargily.':'Le parcours vous redirigerait vers Chargily pour payer avec CIB ou Edahabia.';$('#payment-result').textContent=''}));
$('#simulate').addEventListener('click',()=>{$('#payment-result').textContent=$('[name=payment]:checked').value==='manual'?'Simulation CCP / BaridiMob terminée. Aucun virement à effectuer, aucune commande créée.':'Simulation Chargily terminée. Aucune carte sollicitée, aucun paiement ni commande créés.'});
$('#menu').addEventListener('click',()=>{const open=$('#menu').getAttribute('aria-expanded')!=='true';$('#menu').setAttribute('aria-expanded',open);$('#nav').classList.toggle('open',open)});document.querySelectorAll('#nav a').forEach(a=>a.addEventListener('click',()=>{$('#nav').classList.remove('open');$('#menu').setAttribute('aria-expanded','false')}));
renderDeck();renderCatalog();renderCart();
try{motion=await import('../assets/vendor/motion.js');if(!reduced){motion.animate('.hero h1',{clipPath:['inset(0 0 100% 0)','inset(0 0 0% 0)']},{duration:1,ease:[.16,1,.3,1]});motion.animate('.deck-card',{opacity:[.2,1],filter:['blur(5px)','blur(0px)']},{duration:.8,delay:motion.stagger(.1)});motion.inView('.endnote',()=>motion.animate('.end-flower',{rotate:[-18,72]},{duration:1.3,ease:[.16,1,.3,1]}),{amount:.3})}}catch{ /* Shopping remains available if optional motion cannot load. */ }
