const base='../assets/products/';
const covers={elden:'elden-ring.jpg',cyber:'cyberpunk.jpg',reddead:'red-dead.jpg',witcher:'hollow-knight.jpg',split:'split-fiction.jpg',forza:'forza.jpg'};
document.querySelectorAll('[data-cover]').forEach(img=>img.src=base+covers[img.dataset.cover]);
const products=[
{id:'elden',name:'Elden Ring',category:'steam',label:'Compte Steam',image:'elden-ring.jpg',variants:[['Édition standard',3900],['Édition Deluxe',4900]]},
{id:'cyber',name:'Cyberpunk 2077',category:'steam',label:'Compte Steam',image:'cyberpunk.jpg',variants:[['Édition standard',2900],['Édition Ultimate',4500]]},
{id:'gift',name:'Carte cadeau Steam',category:'gift',label:'Crédit pour votre bibliothèque',image:'steam-gift.jpg',variants:[['Valeur exemple · 10 USD',2400],['Valeur exemple · 20 USD',4600],['Valeur exemple · 50 USD',11000]]},
{id:'xbox',name:'Xbox Game Pass',category:'xbox',label:'Votre prochain jeu vous attend',image:'xbox.jpg',variants:[['PC · 1 mois',1900],['Ultimate · 1 mois',2900]]},
{id:'netflix',name:'Netflix',category:'netflix',label:'Une bonne raison de rester',image:'netflix.jpg',variants:[['Abonnement · 1 mois',1200],['Abonnement · 3 mois',3300]]},
{id:'spotify',name:'Spotify Premium',category:'spotify',label:'La bande-son de vos journées',image:'spotify.jpg',variants:[['Personnel · 1 mois',700],['Personnel · 3 mois',1900]]},
{id:'exitlag',name:'ExitLag',category:'exitlag',label:'Pour vos sessions en ligne',image:'exitlag.jpg',variants:[['Abonnement · 1 mois',1100],['Abonnement · 3 mois',2900]]},
{id:'reddead',name:'Red Dead Redemption 2',category:'steam',label:'Compte Steam',image:'red-dead.jpg',variants:[['Édition standard',2500],['Édition Ultimate',3400]]}
];
let selectedFilter='all',cart=[],featureIndex=0,toastTimer;
const money=n=>new Intl.NumberFormat('fr-DZ').format(n)+' DA';
const plus='<svg viewBox="0 0 24 24"><path d="M5 12h14M12 5v14"/></svg>';
const productDialog=document.querySelector('#product-dialog'),cartDialog=document.querySelector('#cart-dialog');
let motion=null;
function renderProducts(){const query=document.querySelector('#search').value.trim().toLocaleLowerCase('fr');const visible=products.filter(p=>(selectedFilter==='all'||p.category===selectedFilter)&&`${p.name} ${p.label}`.toLocaleLowerCase('fr').includes(query));document.querySelector('#products').innerHTML=visible.map(p=>`<button class="product" data-product="${p.id}" aria-label="Choisir ${p.name}"><div class="product-visual"><img src="${base+p.image}" alt="${p.name}" loading="lazy"><span class="product-add">${plus}</span></div><div class="product-meta"><h3>${p.name}</h3><span class="product-price">Dès ${money(p.variants[0][1])}</span></div><p class="product-label">${p.label}</p></button>`).join('');document.querySelector('#empty').hidden=visible.length>0;if(motion&&!reduceMotion)motion.animate('.product-visual',{clipPath:['inset(0 0 12% 0)','inset(0 0 0% 0)']},{duration:.45,delay:motion.stagger(.045)});}
function setFilter(filter){selectedFilter=filter;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter===filter);b.setAttribute('aria-pressed',String(b.dataset.filter===filter))});renderProducts();}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));
document.querySelector('#search').addEventListener('input',renderProducts);
document.querySelector('#explore-steam').addEventListener('click',()=>{document.querySelector('#search').value='';setFilter('steam');document.querySelector('#collection').scrollIntoView({behavior:reduceMotion?'instant':'smooth'});});
function openProduct(id){const p=products.find(p=>p.id===id);document.querySelector('.product-dialog-content').innerHTML=`<img class="detail-image" src="${base+p.image}" alt="${p.name}"><div class="detail-copy"><p>${p.label}</p><h2 id="product-title">${p.name}</h2><p>Choisissez votre formule. La région, la compatibilité et les conditions d’accès seront à confirmer avant un achat réel.</p><label for="variant">Votre formule<select id="variant">${p.variants.map((v,i)=>`<option value="${i}">${v[0]}</option>`).join('')}</select></label><div class="detail-price">${money(p.variants[0][1])}</div><button class="primary" id="add-to-cart">Ajouter au panier ${plus}</button><p class="detail-note">Prix et formules illustratifs. Aucun produit ne sera livré dans cette démonstration.</p></div>`;document.querySelector('#variant').addEventListener('change',e=>document.querySelector('.detail-price').textContent=money(p.variants[+e.target.value][1]));document.querySelector('#add-to-cart').addEventListener('click',()=>{const variant=+document.querySelector('#variant').value;const existing=cart.find(i=>i.id===id&&i.variant===variant);if(existing)existing.quantity++;else cart.push({id,variant,quantity:1});updateCount();productDialog.close();toast(`${p.name} ajouté à votre sélection.`);});productDialog.showModal();}
document.querySelector('#products').addEventListener('click',e=>{const b=e.target.closest('[data-product]');if(b)openProduct(b.dataset.product)});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
for(const dialog of [productDialog,cartDialog])dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
function updateCount(){document.querySelector('.cart-count').textContent=cart.reduce((s,i)=>s+i.quantity,0);}
function total(){return cart.reduce((sum,i)=>sum+products.find(p=>p.id===i.id).variants[i.variant][1]*i.quantity,0);}
function renderCart(){document.querySelector('#cart-content').innerHTML=cart.length?`<div class="cart-items">${cart.map((i,index)=>{const p=products.find(p=>p.id===i.id),v=p.variants[i.variant];return `<article class="cart-item"><img src="${base+p.image}" alt=""><div><h3>${p.name}</h3><p>${v[0]}</p><div class="quantity"><button data-quantity="${index}" data-delta="-1" aria-label="Diminuer la quantité de ${p.name}">−</button><span>${i.quantity}</span><button data-quantity="${index}" data-delta="1" aria-label="Augmenter la quantité de ${p.name}">+</button></div><button class="remove-item" data-remove="${index}">Retirer</button></div><span class="cart-item-price">${money(v[1]*i.quantity)}</span></article>`}).join('')}</div><div class="cart-total"><span>Total</span><span>${money(total())}</span></div><p class="checkout-note">Prix illustratifs en DZD. Démonstration uniquement : aucun achat, paiement ou envoi de produit.</p><button class="primary checkout" id="checkout">Choisir le paiement <svg viewBox="0 0 24 24"><path d="M4 12h15m-6-6 6 6-6 6"/></svg></button>`:`<div class="cart-empty"><h3>Le début d’une belle soirée.</h3><p>Votre panier est encore vide. Trouvez votre prochain coup de cœur dans la collection.</p><button class="primary" id="continue-shopping">Explorer la collection</button></div>`;}
document.querySelector('.cart-open').addEventListener('click',()=>{renderCart();cartDialog.showModal()});
document.querySelector('#cart-content').addEventListener('click',e=>{const quantity=e.target.closest('[data-quantity]'),remove=e.target.closest('[data-remove]');if(quantity){const index=+quantity.dataset.quantity;cart[index].quantity+=+quantity.dataset.delta;if(cart[index].quantity<=0)cart.splice(index,1);updateCount();renderCart();}if(remove){cart.splice(+remove.dataset.remove,1);updateCount();renderCart();}if(e.target.closest('#continue-shopping')){cartDialog.close();document.querySelector('#collection').scrollIntoView();}if(e.target.closest('#checkout'))renderCheckout();if(e.target.closest('#payment-back'))renderCart();if(e.target.closest('#finish-demo')){cart=[];updateCount();cartDialog.close();toast('Démonstration terminée. Aucun paiement effectué.');}});
function renderCheckout(){document.querySelector('#cart-content').innerHTML=`<button class="payment-back" id="payment-back">Revenir à ma sélection</button><form class="payment-form"><h3>Comment souhaitez-vous régler ?</h3><div class="cart-total"><span>Total indicatif</span><span>${money(total())}</span></div><fieldset><legend>Paiement en ligne · via Chargily</legend><label><input type="radio" name="payment" value="CIB" checked>Carte CIB</label><label><input type="radio" name="payment" value="Edahabia">Carte Edahabia</label></fieldset><fieldset><legend>Transfert manuel · séparé de Chargily</legend><label><input type="radio" name="payment" value="CCP">Virement CCP</label><label><input type="radio" name="payment" value="BaridiMob">Transfert BaridiMob</label></fieldset><p class="checkout-note" id="payment-description">Un paiement réel ouvrirait le service Chargily. Cette maquette ne demande aucune donnée bancaire.</p><p class="checkout-note">Prix et formules illustratifs. La disponibilité, la région et la livraison restent à confirmer.</p><button class="primary" type="submit">Simuler la commande</button></form>`;document.querySelector('.payment-form').addEventListener('change',e=>{const manual=['CCP','BaridiMob'].includes(e.target.value);document.querySelector('#payment-description').textContent=manual?'Un transfert manuel nécessiterait des instructions et une vérification du règlement. Ce circuit est distinct de Chargily. Aucun transfert à effectuer ici.':'Un paiement réel ouvrirait le service Chargily. Cette maquette ne demande aucune donnée bancaire.';});document.querySelector('.payment-form').addEventListener('submit',e=>{e.preventDefault();const method=new FormData(e.target).get('payment');document.querySelector('#cart-content').innerHTML=`<div class="demo-result"><h3>Votre soirée<br>peut attendre.<br><em>C’était une démo.</em></h3><p>Simulation terminée avec ${method}${['CCP','BaridiMob'].includes(method)?' — transfert manuel':' via Chargily'}. Aucun paiement n’a été effectué et aucune commande réelle n’a été créée.</p><button class="primary" id="finish-demo">Retour à la collection</button></div>`;});}
function toast(message){const element=document.querySelector('#toast');element.textContent=message;element.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>element.classList.remove('show'),3500);}
const menu=document.querySelector('.menu-toggle');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));document.querySelector('#navigation').classList.toggle('open',open)});document.querySelectorAll('#navigation a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');document.querySelector('#navigation').classList.remove('open')}));
const features=[{name:'Elden Ring',image:'elden-ring.jpg'},{name:'Cyberpunk 2077',image:'cyberpunk.jpg'},{name:'Red Dead Redemption 2',image:'red-dead.jpg'}];
function switchFeature(delta){featureIndex=(featureIndex+delta+features.length)%features.length;const feature=features[featureIndex],cover=document.querySelector('.cover-c');cover.src=base+feature.image;cover.alt=feature.name;document.querySelector('#feature-title').textContent=feature.name;if(motion&&!reduceMotion){motion.animate(cover,{clipPath:['inset(0 100% 0 0)','inset(0 0% 0 0)'],rotate:[-1,-3]},{duration:.6,ease:[.16,1,.3,1]});motion.animate('#feature-title',{y:[9,0],opacity:[.5,1]},{duration:.4});}}
document.querySelector('#previous-feature').addEventListener('click',()=>switchFeature(-1));document.querySelector('#next-feature').addEventListener('click',()=>switchFeature(1));
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
renderProducts();
try{motion=await import('../assets/vendor/motion.js');if(!reduceMotion){motion.animate('.hero h1',{clipPath:['inset(0 0 100% 0)','inset(0 0 0% 0)']},{duration:1.1,ease:[.16,1,.3,1]});motion.animate('.wall-cover',{y:[45,0],opacity:[.4,1]},{duration:1.3,delay:motion.stagger(.1),ease:[.16,1,.3,1]});motion.inView('.interlude',()=>{motion.animate('.interlude-image img',{scale:[1.12,1]},{duration:1.5,ease:[.16,1,.3,1]});},{amount:.25});document.querySelector('.cover-stage').addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const rect=e.currentTarget.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width-.5,y=(e.clientY-rect.top)/rect.height-.5;motion.animate('.cover-wall',{x:x*13,y:y*10},{duration:.5});});document.querySelector('.cover-stage').addEventListener('pointerleave',()=>motion.animate('.cover-wall',{x:0,y:0},{duration:.7}));}}catch(error){console.info('Présentation statique disponible.');}
