const products=[
{id:'steam',name:'Comptes Steam',category:'jeu',label:'Jeux PC',description:'Une porte ouverte sur de nouveaux mondes.',image:'steam',variants:[['Forza Horizon 5',3900],['Elden Ring',4900],['Red Dead Redemption 2',3500]]},
{id:'steam-gift',name:'Cartes Steam',category:'jeu',label:'Cartes cadeaux',description:'La liberté de choisir sa prochaine aventure.',image:'steam-gift',variants:[['Crédit 10 USD',2500],['Crédit 20 USD',4900],['Crédit 50 USD',12000]]},
{id:'xbox',name:'Xbox Game Pass',category:'jeu',label:'Abonnement gaming',description:'Changez de jeu. Gardez votre curiosité.',image:'xbox',variants:[['PC · 1 mois',1800],['Ultimate · 1 mois',2900]]},
{id:'netflix',name:'Netflix',category:'stream',label:'Films & séries',description:'Ce soir, partez sans quitter le canapé.',image:'netflix',variants:[['Standard · 1 mois',1200],['Premium · 1 mois',1800]]},
{id:'spotify',name:'Spotify Premium',category:'musique',label:'Musique & podcasts',description:'La bande-son de toutes vos escapades.',image:'spotify',variants:[['Personnel · 1 mois',650],['Personnel · 3 mois',1800]]},
{id:'exitlag',name:'ExitLag',category:'jeu',label:'Outil gaming',description:'Explorez une autre route pour votre connexion.',image:'exitlag',variants:[['1 mois',1500],['3 mois',4000]]}
];
const features=[{name:'Forza Horizon 5',kind:'Compte Steam · Course',description:'Direction le Mexique. Prenez la route.',image:'forza-wide',alt:'Paysage et voiture de Forza Horizon 5',price:3900},{name:'Elden Ring',kind:'Compte Steam · Action RPG',description:'L’Entre-terre vous ouvre ses portes.',image:'elden-wide',alt:'Univers fantastique d’Elden Ring',price:4900},{name:'Red Dead Redemption 2',kind:'Compte Steam · Aventure',description:'Le grand Ouest, à votre rythme.',image:'red-dead-wide',alt:'Paysage de Red Dead Redemption 2',price:3500}];
const money=n=>new Intl.NumberFormat('fr-DZ').format(n)+' DZD';
let activeFilter='all',featured=0,cart=[];const selected={};const $=s=>document.querySelector(s);const catalog=$('#products');let animator;
function renderProducts(){const query=$('#search').value.trim().toLocaleLowerCase('fr');const found=products.filter(p=>(activeFilter==='all'||p.category===activeFilter)&&(`${p.name} ${p.label} ${p.variants.map(v=>v[0]).join(' ')}`).toLocaleLowerCase('fr').includes(query));catalog.innerHTML=found.map(p=>{const v=selected[p.id]||0;return `<article class="ticket" data-product="${p.id}"><img class="ticket-art" src="../assets/products/${p.image}.jpg" alt="${p.name}" loading="lazy"><div class="ticket-info"><h3>${p.name}</h3><span class="category">${p.label}</span><p>${p.description}</p></div><div class="ticket-variant"><label for="variant-${p.id}">Votre formule</label><select id="variant-${p.id}" data-variant="${p.id}">${p.variants.map((v,i)=>`<option value="${i}" ${i===(selected[p.id]||0)?'selected':''}>${v[0]}</option>`).join('')}</select></div><div class="ticket-buy"><span class="ticket-price" id="price-${p.id}">${money(p.variants[v][1])}</span><button class="button" data-add="${p.id}" aria-label="Ajouter ${p.name} au panier">Ajouter <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg></button></div></article>`}).join('');$('#empty').hidden=found.length>0;}
renderProducts();
$('#search').addEventListener('input',renderProducts);
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{activeFilter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});renderProducts()}));
catalog.addEventListener('change',e=>{if(!e.target.matches('[data-variant]'))return;const id=e.target.dataset.variant;selected[id]=Number(e.target.value);$(`#price-${id}`).textContent=money(products.find(p=>p.id===id).variants[selected[id]][1])});
catalog.addEventListener('click',e=>{const button=e.target.closest('[data-add]');if(button)addItem(button.dataset.add,selected[button.dataset.add]||0)});
function addItem(id,index){const product=products.find(p=>p.id===id),variant=product.variants[index],key=`${id}:${index}`,existing=cart.find(p=>p.key===key);if(existing)existing.quantity++;else cart.push({key,name:product.name,variant:variant[0],price:variant[1],quantity:1});renderCart();$('#checkout-status').textContent='';$('#toast').textContent=`${product.name} — ${variant[0]} ajouté au panier`;$('#toast').classList.add('visible');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2800)}
function renderCart(){const count=cart.reduce((n,p)=>n+p.quantity,0);$('#cart-count').textContent=count;$('#cart-items').innerHTML=cart.length?cart.map(p=>`<div class="cart-line"><div><strong>${p.name}</strong><p>${p.variant} · Quantité : ${p.quantity}</p><button data-remove="${p.key}" aria-label="Retirer un exemplaire de ${p.name}, ${p.variant}">Retirer un exemplaire</button></div><span>${money(p.price*p.quantity)}</span></div>`).join(''):'<p class="cart-empty">Votre itinéraire est encore libre. Ajoutez une destination pour commencer.</p>';$('#cart-total').textContent=money(cart.reduce((n,p)=>n+p.price*p.quantity,0));$('#checkout-button').disabled=!count}
$('#cart-items').addEventListener('click',e=>{const button=e.target.closest('[data-remove]');if(!button)return;const key=button.dataset.remove,item=cart.find(p=>p.key===key);item.quantity--;cart=cart.filter(p=>p.quantity>0);renderCart();$('#checkout-status').textContent='';const next=$(`[data-remove="${key}"]`)||$('#close-cart');next.focus()});
const dialog=$('#cart');$('.cart-toggle').addEventListener('click',()=>{renderCart();dialog.showModal();$('.cart-toggle').setAttribute('aria-expanded','true')});$('#close-cart').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>$('.cart-toggle').setAttribute('aria-expanded','false'));dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
$('#checkout').addEventListener('submit',e=>{e.preventDefault();if(!cart.length)return;const manual=new FormData(e.target).get('payment')==='manual';$('#checkout-status').textContent=manual?'Simulation : un transfert CCP / BaridiMob suivrait un parcours manuel avec vérification. Aucun transfert à effectuer, aucune commande créée.':'Simulation : le paiement CIB / Edahabia passerait par Chargily. Le service n’est pas connecté ; aucun paiement effectué, aucune commande créée.'});$('#checkout').addEventListener('change',()=>$('#checkout-status').textContent='');
document.querySelectorAll('[data-feature]').forEach(button=>button.addEventListener('click',()=>{featured=Number(button.dataset.feature);const f=features[featured];document.querySelectorAll('[data-feature]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});$('#feature-title').textContent=f.name;$('#feature-platform').textContent=f.kind;$('#feature-description').textContent=f.description;$('#feature-price').textContent=money(f.price);$('.window-one').src=`../assets/products/${f.image}.jpg`;$('.window-one').alt=f.alt;const next=features[(featured+1)%features.length];$('.window-two').src=`../assets/products/${next.image}.jpg`;$('.window-two').alt=next.alt;if(animator&&!matchMedia('(prefers-reduced-motion: reduce)').matches)animator('.window-one',{clipPath:['inset(0 100% 0 0)','inset(0 0% 0 0)']},{duration:.6,ease:[.16,1,.3,1]})}));$('#feature-add').addEventListener('click',()=>addItem('steam',featured));
$('.menu').addEventListener('click',()=>{const open=$('#navigation').classList.toggle('open');$('.menu').setAttribute('aria-expanded',String(open))});$('#navigation').addEventListener('click',e=>{if(e.target.closest('a')){$('#navigation').classList.remove('open');$('.menu').setAttribute('aria-expanded','false')}});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){import('../assets/vendor/motion.js').then(({animate,stagger,inView})=>{animator=animate;animate('.hero h1',{clipPath:['inset(0 0 100% 0)','inset(0 0 0% 0)'],y:[24,0]},{duration:1,ease:[.16,1,.3,1]});animate('.image-windows img',{y:[48,0],rotate:[3,0]},{duration:1.2,delay:stagger(.12),ease:[.16,1,.3,1]});animate('.featured',{x:[-50,0],clipPath:['inset(0 5% 0 0)','inset(0 0% 0 0)']},{duration:.9,delay:.15,ease:[.16,1,.3,1]});inView('.products',()=>{animate('.ticket',{x:[22,0]},{duration:.7,delay:stagger(.06),ease:[.16,1,.3,1]})})}).catch(()=>{})}
