import { animate } from '../assets/vendor/motion.js';
const products=[
{id:'steam',name:'Compte Steam',kind:'Un jeu, un autre monde.',category:'jeux',image:'steam.jpg',variants:[['Hollow Knight',1400],['Forza Horizon 5',3200],['Elden Ring',4800]]},
{id:'steam-gift',name:'Carte cadeau Steam',kind:'À offrir. Ou à s’offrir.',category:'jeux',image:'steam-gift.jpg',variants:[['5 USD',1250],['10 USD',2400],['20 USD',4700]]},
{id:'xbox',name:'Xbox Game Pass',kind:'De nouvelles parties.',category:'jeux',image:'xbox.jpg',variants:[['PC · 1 mois',1800],['Ultimate · 1 mois',2800],['Ultimate · 3 mois',7500]]},
{id:'netflix',name:'Netflix',kind:'Le prochain épisode.',category:'films',image:'netflix.jpg',variants:[['1 mois',900],['3 mois',2500],['6 mois',4800]]},
{id:'spotify',name:'Spotify Premium',kind:'Le son de vos journées.',category:'musique',image:'spotify.jpg',variants:[['1 mois',650],['3 mois',1800],['12 mois',6200]]},
{id:'exitlag',name:'ExitLag',kind:'Pensé pour vos sessions.',category:'jeux',image:'exitlag.jpg',variants:[['1 mois',1100],['3 mois',3000],['12 mois',10000]]}
];
const money=n=>new Intl.NumberFormat('fr-DZ').format(n)+' DA';let filter='all';const selected={};let cart=[];const $=s=>document.querySelector(s);const dialog=$('#cart-dialog');
function renderProducts(){const query=$('#search').value.trim().toLocaleLowerCase('fr');const list=products.filter(p=>(filter==='all'||p.category===filter)&&`${p.name} ${p.kind}`.toLocaleLowerCase('fr').includes(query));$('#result-count').textContent=`${list.length} objet${list.length===1?'':'s'}`;$('#product-list').innerHTML=list.length?list.map(p=>{const i=selected[p.id]||0;return `<article class="product" data-product="${p.id}"><img class="product-image" src="../assets/products/${p.image}" alt="${p.name}" loading="lazy"><div><h3>${p.name}</h3><p class="kind">${p.kind}</p><select data-variant="${p.id}" aria-label="Formule ${p.name}">${p.variants.map((v,n)=>`<option value="${n}" ${n===i?'selected':''}>${v[0]}</option>`).join('')}</select></div><div class="product-action"><strong class="price">${money(p.variants[i][1])}</strong><button class="add" data-add="${p.id}" aria-label="Ajouter ${p.name} au panier">Ajouter<svg viewBox="0 0 24 24"><path d="M12 4v16M4 12h16"/></svg></button></div></article>`}).join(''):'<p class="empty">Aucun essentiel trouvé. Essayez un autre mot ou « Tout voir ».</p>'}
$('.categories').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',String(el===b))});renderProducts()});$('#search').addEventListener('input',renderProducts);$('#product-list').addEventListener('change',e=>{if(!e.target.matches('[data-variant]'))return;const id=e.target.dataset.variant;selected[id]=Number(e.target.value);const p=products.find(p=>p.id===id);e.target.closest('.product').querySelector('.price').textContent=money(p.variants[selected[id]][1])});
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600)}
$('#product-list').addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(!b)return;const p=products.find(p=>p.id===b.dataset.add),variant=selected[p.id]||0,key=p.id+'-'+variant,line=cart.find(l=>l.key===key);if(line)line.qty++;else cart.push({key,id:p.id,variant,qty:1});updateCount();toast(`${p.name} ajouté à vos essentiels.`)});function updateCount(){$('#cart-count').textContent=cart.reduce((s,l)=>s+l.qty,0)}
function renderCart(){const total=cart.reduce((s,l)=>s+products.find(p=>p.id===l.id).variants[l.variant][1]*l.qty,0);$('#cart-content').innerHTML=cart.length?cart.map(l=>{const p=products.find(p=>p.id===l.id),v=p.variants[l.variant];return `<div class="cart-line"><div><h3>${p.name}</h3><p>${v[0]} · Quantité ${l.qty}</p><button data-remove="${l.key}" aria-label="Retirer ${p.name} ${v[0]}">Retirer</button></div><strong>${money(v[1]*l.qty)}</strong></div>`}).join('')+`<div class="total"><span>Total</span><strong>${money(total)}</strong></div><p class="note">Prix illustratifs. Aucun achat réel.</p><fieldset><legend>Choisir un mode de paiement</legend><label><input type="radio" name="payment" value="card" checked> CIB / Edahabia — via Chargily</label><label><input type="radio" name="payment" value="manual"> CCP / BaridiMob — transfert manuel</label></fieldset><p id="payment-help">Simulation du parcours Chargily. Aucune donnée bancaire ne sera demandée.</p><button class="checkout" id="checkout">Simuler le paiement par carte</button>`:'<p class="empty">Votre panier attend son premier essentiel.</p><button class="checkout" id="continue-shopping">Découvrir la collection</button>'}
$('#cart-open').addEventListener('click',()=>{renderCart();dialog.showModal()});$('#cart-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});$('#cart-content').addEventListener('change',e=>{if(e.target.name!=='payment')return;const manual=e.target.value==='manual';$('#payment-help').textContent=manual?'Circuit manuel séparé de Chargily. Dans la boutique finale, le transfert serait vérifié après réception du justificatif. Aucun transfert à effectuer ici.':'Simulation du parcours Chargily. Aucune donnée bancaire ne sera demandée.';$('#checkout').textContent=manual?'Simuler les instructions de transfert':'Simuler le paiement par carte'});$('#cart-content').addEventListener('click',e=>{const remove=e.target.closest('[data-remove]');if(remove){cart=cart.filter(l=>l.key!==remove.dataset.remove);updateCount();renderCart();return}if(e.target.id==='continue-shopping'){dialog.close();$('#catalog').scrollIntoView();return}if(e.target.id==='checkout'){const manual=$('input[name="payment"]:checked').value==='manual';$('#cart-content').innerHTML=`<div class="success"><h3>${manual?'Le transfert, étape par étape.':'Parcours carte simulé.'}</h3><p>${manual?'Dans la boutique finale : réception des coordonnées CCP, transfert par CCP ou BaridiMob, puis envoi du justificatif pour vérification manuelle. Aucun numéro de compte ni transfert réel dans cette démonstration.':'Une boutique connectée ouvrirait le paiement CIB ou Edahabia via Chargily. Cette démonstration s’arrête ici, sans redirection ni débit.'}</p><p class="note">Aucune commande réelle créée. Votre panier est conservé.</p></div><button class="checkout" id="back-cart">Revenir au panier</button>`}if(e.target.id==='back-cart')renderCart()});
$('#menu-toggle').addEventListener('click',()=>{const expanded=$('#menu-toggle').getAttribute('aria-expanded')==='true';$('#menu-toggle').setAttribute('aria-expanded',String(!expanded));$('#navigation').classList.toggle('open',!expanded)});$('#navigation').addEventListener('click',e=>{if(e.target.closest('a')){$('#navigation').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false')}});
renderProducts();const reduce=matchMedia('(prefers-reduced-motion: reduce)');let floating=[];let paused=reduce.matches;function setMotion(){floating.forEach(a=>a.stop());floating=[];if(!paused&&!reduce.matches){document.querySelectorAll('.object').forEach((el,i)=>floating.push(animate(el,{y:[0,-12,0]},{duration:5+i,repeat:Infinity,ease:'easeInOut',delay:i*.5})))}$('#motion-toggle').textContent=paused?'Reprendre l’animation':'Mettre en pause';$('#motion-toggle').setAttribute('aria-pressed',String(paused))}if(!reduce.matches){animate('.hero h1',{clipPath:['inset(0 0 100% 0)','inset(0 0 0 0)']},{duration:1.2,ease:[.16,1,.3,1]});animate('.exhibit',{opacity:[.35,1],y:[35,0]},{duration:1.3,ease:[.16,1,.3,1]})}setMotion();$('#motion-toggle').addEventListener('click',()=>{paused=!paused;setMotion()});reduce.addEventListener('change',()=>{paused=reduce.matches;setMotion()});
