const asset='../assets/products/';
const products=[
{id:'steam',name:'Comptes Steam',description:'Le prochain monde à explorer.',label:'Choisissez votre jeu',variants:[{name:'Forza Horizon 5',price:3200,image:'forza.jpg'},{name:'Elden Ring',price:3900,image:'elden-ring.jpg'},{name:'Red Dead Redemption 2',price:2500,image:'red-dead.jpg'}]},
{id:'gift',name:'Cartes Steam',description:'De nouvelles possibilités dans votre bibliothèque.',label:'Choisissez un montant',variants:[{name:'Valeur exemple · 10 USD',price:2400,image:'steam-gift.jpg'},{name:'Valeur exemple · 20 USD',price:4600,image:'steam-gift.jpg'},{name:'Valeur exemple · 50 USD',price:11000,image:'steam-gift.jpg'}]},
{id:'xbox',name:'Xbox Game Pass',description:'Changez de jeu. Gardez le plaisir.',label:'Choisissez votre formule',variants:[{name:'PC · 1 mois',price:1900,image:'xbox.jpg'},{name:'Ultimate · 1 mois',price:2900,image:'xbox.jpg'}]},
{id:'netflix',name:'Netflix',description:'Votre soirée a trouvé son programme.',label:'Choisissez une durée',variants:[{name:'Abonnement · 1 mois',price:1200,image:'netflix.jpg'},{name:'Abonnement · 3 mois',price:3300,image:'netflix.jpg'}]},
{id:'spotify',name:'Spotify Premium',description:'La bonne bande-son, au bon moment.',label:'Choisissez une durée',variants:[{name:'Personnel · 1 mois',price:700,image:'spotify.jpg'},{name:'Personnel · 3 mois',price:1900,image:'spotify.jpg'}]},
{id:'exitlag',name:'ExitLag',description:'Un outil pour vos sessions en ligne.',label:'Choisissez une durée',variants:[{name:'Abonnement · 1 mois',price:1100,image:'exitlag.jpg'},{name:'Abonnement · 3 mois',price:2900,image:'exitlag.jpg'}]}
];
const features=[{title:'Forza Horizon 5',word:'FORZA.',image:'forza-wide.jpg',copy:'Changez d’horizon.<br>La route est à vous.'},{title:'Elden Ring',word:'ELDEN RING.',image:'elden-wide.jpg',copy:'Prenez une autre route.<br>Entrez dans l’Entre-terre.'},{title:'Red Dead Redemption 2',word:'RED DEAD.',image:'red-dead-wide.jpg',copy:'Direction le grand Ouest.<br>Une autre vie vous attend.'}];
const arrow='<svg viewBox="0 0 24 24"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>';
const money=n=>new Intl.NumberFormat('fr-DZ').format(n)+' DA';
let selected='steam',selectedVariants={steam:0,gift:0,xbox:0,netflix:0,spotify:0,exitlag:0},featureIndex=0,cart=[],motion=null,toastTimer;
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const cartDialog=document.querySelector('#cart-dialog');
function renderIndex(){const query=document.querySelector('#search').value.trim().toLocaleLowerCase('fr');const visible=products.filter(p=>`${p.name} ${p.description} ${p.variants.map(v=>v.name).join(' ')}`.toLocaleLowerCase('fr').includes(query));document.querySelector('#product-index').innerHTML=visible.map(p=>`<button class="index-row ${selected===p.id?'selected':''}" data-product="${p.id}" aria-pressed="${selected===p.id}" aria-controls="configurator"><div><h3>${p.name}</h3><p>${p.description}</p></div>${arrow}</button>`).join('');document.querySelector('#empty').hidden=!!visible.length;document.querySelector('#configurator').hidden=!visible.length;}
function renderConfig(animate=false){document.querySelector('#configurator').classList.toggle('brand-preview',selected!=='steam');const product=products.find(p=>p.id===selected),variant=product.variants[selectedVariants[selected]];document.querySelector('#configurator').innerHTML=`<div class="preview-image"><img src="${asset+variant.image}" alt="${product.id==='steam'?variant.name:product.name}"></div><div class="config-heading"><div><h3>${product.id==='steam'?variant.name:product.name}</h3><p>${product.id==='steam'?'Compte Steam':variant.name}</p></div><span class="config-price">${money(variant.price)}</span></div><label class="variant-label" for="variant">${product.label}<select id="variant">${product.variants.map((v,i)=>`<option value="${i}" ${i===selectedVariants[selected]?'selected':''}>${v.name}</option>`).join('')}</select></label><button class="solid" id="add-to-cart">Ajouter à votre panier ${arrow}</button><p class="config-note">Prix et formules illustratifs. Région, compatibilité, disponibilité et conditions d’accès à confirmer avant tout achat réel.</p>`;if(animate&&motion&&!reduceMotion){motion.animate('.preview-image img',{clipPath:['inset(0 100% 0 0)','inset(0 0% 0 0)'],scale:[1.04,1]},{duration:.65,ease:[.16,1,.3,1]});}}
function selectProduct(id,move=false){selected=id;renderIndex();renderConfig(true);if(move)document.querySelector('#configurator').scrollIntoView({behavior:reduceMotion?'instant':'smooth',block:'center'});}
document.querySelector('#product-index').addEventListener('click',e=>{const row=e.target.closest('[data-product]');if(!row)return;selectProduct(row.dataset.product,matchMedia('(max-width:760px)').matches);document.querySelector(`[data-product="${selected}"]`)?.focus({preventScroll:true});});
document.querySelector('#search').addEventListener('input',()=>{renderIndex();const query=document.querySelector('#search').value.trim().toLocaleLowerCase('fr');if(query){const matched=products.find(p=>`${p.name} ${p.description} ${p.variants.map(v=>v.name).join(' ')}`.toLocaleLowerCase('fr').includes(query));if(matched&&matched.id!==selected){selected=matched.id;renderIndex();renderConfig(true);}}});
document.querySelector('#configurator').addEventListener('change',e=>{if(e.target.id==='variant'){selectedVariants[selected]=+e.target.value;const product=products.find(p=>p.id===selected),variant=product.variants[+e.target.value];document.querySelector('.preview-image img').src=asset+variant.image;document.querySelector('.preview-image img').alt=selected==='steam'?variant.name:product.name;document.querySelector('.config-heading h3').textContent=selected==='steam'?variant.name:product.name;document.querySelector('.config-heading p').textContent=selected==='steam'?'Compte Steam':variant.name;document.querySelector('.config-price').textContent=money(variant.price);if(motion&&!reduceMotion)motion.animate('.preview-image img',{clipPath:['inset(0 0 0 100%)','inset(0 0 0 0%)']},{duration:.5,ease:[.16,1,.3,1]});}});
document.querySelector('#configurator').addEventListener('click',e=>{if(!e.target.closest('#add-to-cart'))return;const variant=selectedVariants[selected],existing=cart.find(i=>i.id===selected&&i.variant===variant),product=products.find(p=>p.id===selected);if(existing)existing.quantity++;else cart.push({id:selected,variant,quantity:1});updateCount();toast(`${selected==='steam'?product.variants[variant].name:product.name} ajouté au panier.`);});
function switchFeature(delta){featureIndex=(featureIndex+delta+features.length)%features.length;const feature=features[featureIndex],image=document.querySelector('#feature-image');image.src=asset+feature.image;image.alt=feature.title;document.querySelector('#feature-title').textContent=feature.title;document.querySelector('.feature-word').textContent=feature.word;document.querySelector('#feature-price').textContent=money(products[0].variants[featureIndex].price);document.querySelector('.feature-order>p').innerHTML=feature.copy;if(motion&&!reduceMotion){motion.animate(image,{clipPath:['inset(0 100% 0 0)','inset(0 0% 0 0)'],scale:[1.06,1]},{duration:.8,ease:[.16,1,.3,1]});motion.animate('.feature-word',{y:[20,0],opacity:[.5,1]},{duration:.6,ease:[.16,1,.3,1]});}}
document.querySelector('#next-feature').addEventListener('click',()=>switchFeature(1));document.querySelector('#previous-feature').addEventListener('click',()=>switchFeature(-1));
document.querySelector('#choose-feature').addEventListener('click',()=>{selectedVariants.steam=featureIndex;document.querySelector('#search').value='';selectProduct('steam',true);document.querySelector('#variant').focus({preventScroll:true});});
function updateCount(){document.querySelector('.cart-count').textContent=cart.reduce((n,i)=>n+i.quantity,0);}
function cartTotal(){return cart.reduce((n,i)=>n+products.find(p=>p.id===i.id).variants[i.variant].price*i.quantity,0);}
function renderCart(){document.querySelector('#cart-content').innerHTML=cart.length?`${cart.map((item,index)=>{const p=products.find(p=>p.id===item.id),v=p.variants[item.variant];return `<article class="cart-item"><img src="${asset+v.image}" alt=""><div><h3>${p.id==='steam'?v.name:p.name}</h3><p>${p.id==='steam'?'Compte Steam':v.name}</p><div class="quantity"><button data-quantity="${index}" data-delta="-1" aria-label="Diminuer la quantité de ${p.name}">−</button><span>${item.quantity}</span><button data-quantity="${index}" data-delta="1" aria-label="Augmenter la quantité de ${p.name}">+</button></div><button class="remove" data-remove="${index}">Retirer</button></div><span class="item-price">${money(v.price*item.quantity)}</span></article>`}).join('')}<div class="cart-total"><span>Total indicatif</span><span>${money(cartTotal())}</span></div><p class="cart-note">Prix et formules illustratifs. Aucun achat réel ni envoi de produit dans cette démonstration.</p><button class="solid cart-checkout" id="checkout">Choisir votre paiement ${arrow}</button>`:`<div class="cart-empty"><h3>De la place pour vos envies.</h3><p>Votre panier est vide. Explorez la sélection et choisissez votre prochain bon moment.</p><button class="solid" id="continue-shopping">Voir la sélection ${arrow}</button></div>`;}
document.querySelector('.cart-open').addEventListener('click',()=>{renderCart();cartDialog.showModal();});document.querySelector('.close').addEventListener('click',()=>cartDialog.close());cartDialog.addEventListener('click',e=>{if(e.target===cartDialog){const rect=cartDialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)cartDialog.close();}});
document.querySelector('#cart-content').addEventListener('click',e=>{const quantity=e.target.closest('[data-quantity]'),remove=e.target.closest('[data-remove]');if(quantity){const index=+quantity.dataset.quantity;cart[index].quantity+=+quantity.dataset.delta;if(cart[index].quantity<1)cart.splice(index,1);updateCount();renderCart();const next=document.querySelector(`[data-quantity="${Math.min(index,cart.length-1)}"][data-delta="${quantity.dataset.delta}"]`);next?.focus();}if(remove){cart.splice(+remove.dataset.remove,1);updateCount();renderCart();}if(e.target.closest('#checkout'))renderCheckout();if(e.target.closest('#payment-back'))renderCart();if(e.target.closest('#continue-shopping')){cartDialog.close();document.querySelector('#catalog').scrollIntoView();}if(e.target.closest('#finish-demo')){cart=[];updateCount();cartDialog.close();toast('Démonstration terminée. Aucun paiement effectué.');}});
function renderCheckout(){document.querySelector('#cart-content').innerHTML=`<button id="payment-back" class="back">Revenir au panier</button><form class="checkout-form"><h3>Votre moyen de paiement.</h3><div class="cart-total"><span>Total indicatif</span><span>${money(cartTotal())}</span></div><fieldset><legend>En ligne · via Chargily</legend><label><input name="payment" type="radio" value="CIB" checked>Carte CIB</label><label><input name="payment" type="radio" value="Edahabia">Carte Edahabia</label></fieldset><fieldset><legend>Transfert manuel · séparé de Chargily</legend><label><input name="payment" type="radio" value="CCP">Virement CCP</label><label><input name="payment" type="radio" value="BaridiMob">Transfert BaridiMob</label></fieldset><p class="cart-note" id="payment-description">Le parcours réel passerait par Chargily. Cette maquette ne demande aucune information bancaire.</p><p class="cart-note">Prix et formules illustratifs. Stock, région et conditions de livraison à confirmer.</p><button class="solid" type="submit">Simuler cette commande ${arrow}</button></form>`;document.querySelector('.checkout-form').addEventListener('change',e=>{document.querySelector('#payment-description').textContent=['CCP','BaridiMob'].includes(e.target.value)?'Un transfert manuel nécessiterait des instructions et une vérification du règlement. Ce circuit est distinct de Chargily. Aucun transfert à effectuer ici.':'Le parcours réel passerait par Chargily. Cette maquette ne demande aucune information bancaire.';});document.querySelector('.checkout-form').addEventListener('submit',e=>{e.preventDefault();const method=new FormData(e.target).get('payment');document.querySelector('#cart-content').innerHTML=`<div class="demo-result"><h3>Vous avez testé.<br>Rien n’a été débité.</h3><p>Simulation avec ${method}${['CCP','BaridiMob'].includes(method)?' par transfert manuel':' via Chargily'}. Aucune commande réelle n’a été créée et aucun paiement n’a été effectué.</p><button id="finish-demo" class="solid">Retour à la sélection ${arrow}</button></div>`;document.querySelector('#finish-demo').focus();});}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3600);}
const menu=document.querySelector('.menu-toggle');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));document.querySelector('#navigation').classList.toggle('open',open);});document.querySelectorAll('#navigation a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');document.querySelector('#navigation').classList.remove('open');}));
renderIndex();renderConfig();
try{motion=await import('../assets/vendor/motion.js');if(!reduceMotion){motion.animate('.feature-artwork',{clipPath:['inset(0 0 100% 0)','inset(0 0 0% 0)']},{duration:1.2,ease:[.16,1,.3,1]});motion.animate('.hero-heading h1',{y:[18,0],opacity:[.6,1]},{duration:.8,ease:[.16,1,.3,1]});motion.animate('.feature-word',{x:[-25,0]},{duration:1.2,delay:.15,ease:[.16,1,.3,1]});motion.inView('.statement',()=>motion.animate('.statement p',{clipPath:['inset(0 100% 0 0)','inset(0 0% 0 0)']},{duration:.9,ease:[.16,1,.3,1]}),{amount:.4});const frame=document.querySelector('.feature-frame');frame.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const rect=frame.getBoundingClientRect(),position=(e.clientX-rect.left)/rect.width-.5;motion.animate('#feature-image',{scale:1.035,x:position*12},{duration:.7});motion.animate('.feature-word',{x:position*-10},{duration:.6});});frame.addEventListener('pointerleave',()=>{motion.animate('#feature-image',{scale:1,x:0},{duration:.8});motion.animate('.feature-word',{x:0},{duration:.7});});}}catch(error){console.info('Le catalogue reste disponible sans animation.');}
