const products = [
 {id:'steam',name:'Compte Steam',category:'Jeux',image:'steam.jpg',description:'Une nouvelle bibliothèque à explorer.',variants:[['Sélection découverte',1900],['Sélection aventure',3400]]},
 {id:'steam-gift',name:'Carte cadeau Steam',category:'Jeux',image:'steam-gift.jpg',description:'Du crédit pour ta prochaine obsession.',variants:[['Valeur démo · 10 €',2900],['Valeur démo · 20 €',5700]]},
 {id:'xbox',name:'Xbox Game Pass',category:'Jeux',image:'xbox.jpg',description:'Change de jeu. Garde ton envie.',variants:[['1 mois · démo',1800],['3 mois · démo',4900]]},
 {id:'netflix',name:'Netflix',category:'Streaming',image:'netflix.jpg',description:'Ton prochain « encore un épisode ».',variants:[['1 mois · démo',1200],['3 mois · démo',3300]]},
 {id:'spotify',name:'Spotify Premium',category:'Musique',image:'spotify.jpg',description:'La bande-son de toutes tes journées.',variants:[['1 mois · démo',700],['3 mois · démo',1900]]},
 {id:'exitlag',name:'ExitLag',category:'Jeux',image:'exitlag.png',description:'L’outil réseau pensé pour les joueurs.',variants:[['1 mois · démo',1100],['3 mois · démo',3000]]}
];
let category='Tout'; const cart=[];const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('fr-DZ').format(n)+' DZD';
function renderProducts(){const query=$('#search').value.toLocaleLowerCase('fr');const filtered=products.filter(p=>(category==='Tout'||p.category===category)&&(p.name+' '+p.description).toLocaleLowerCase('fr').includes(query));$('#product-grid').innerHTML=filtered.map(p=>`<article class="product" data-product="${p.id}"><div class="product-image"><img src="../assets/products/${p.image}" alt="${p.name}" loading="lazy"><span class="product-category">${p.category}</span></div><div class="product-heading"><h3>${p.name}</h3><span><strong data-price>${money(p.variants[0][1])}</strong></span></div><p>${p.description}</p><div class="product-buy"><select aria-label="Formule ${p.name}">${p.variants.map((v,i)=>`<option value="${i}">${v[0]}</option>`).join('')}</select><button class="add-button" aria-label="Ajouter ${p.name} au panier">Ajouter +</button></div></article>`).join('');$('#empty').hidden=filtered.length>0;}
function setCategory(value){category=value;document.querySelectorAll('[data-category]').forEach(b=>{const active=b.dataset.category===value;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});renderProducts()}
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>setCategory(b.dataset.category)));document.querySelectorAll('[data-jump]').forEach(a=>a.addEventListener('click',()=>{$('#search').value='';setCategory(a.dataset.jump)}));$('#search').addEventListener('input',renderProducts);
$('#product-grid').addEventListener('change',e=>{if(e.target.tagName!=='SELECT')return;const article=e.target.closest('[data-product]');const p=products.find(p=>p.id===article.dataset.product);article.querySelector('[data-price]').textContent=money(p.variants[Number(e.target.value)][1])});
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2700)}
$('#product-grid').addEventListener('click',e=>{const button=e.target.closest('.add-button');if(!button)return;const article=button.closest('[data-product]');const p=products.find(p=>p.id===article.dataset.product);const variant=Number(article.querySelector('select').value);const found=cart.find(item=>item.id===p.id&&item.variant===variant);if(found)found.quantity++;else cart.push({id:p.id,variant,quantity:1});resetCheckout();renderCart();toast(p.name+' ajouté au panier');button.textContent='Ajouté ✓';setTimeout(()=>{button.textContent='Ajouter +'},1100)});
const dialog=$('#cart-dialog');function resetCheckout(){$('#checkout').hidden=true;$('#confirmation').textContent='';$('#confirm-demo').disabled=false}function renderCart(){$('#cart-count').textContent=cart.reduce((n,i)=>n+i.quantity,0);$('#cart-items').innerHTML=cart.length?cart.map((item,index)=>{const p=products.find(p=>p.id===item.id),v=p.variants[item.variant];return `<div class="cart-row"><div><h3>${p.name}</h3><p>${v[0]} · Quantité : ${item.quantity}</p><button data-remove="${index}" aria-label="Retirer ${p.name} du panier">Retirer</button></div><strong class="cart-price">${money(v[1]*item.quantity)}</strong></div>`}).join(''):'<p>Ton panier attend son premier kif.</p><a class="yellow-button full" href="#collection" data-close>Explorer la collection <span aria-hidden="true">→</span></a>';$('#cart-total').textContent=money(cart.reduce((n,i)=>n+products.find(p=>p.id===i.id).variants[i.variant][1]*i.quantity,0));$('#cart-bottom').hidden=!cart.length;}
$('#open-cart').addEventListener('click',()=>{dialog.showModal();document.body.style.overflow='hidden'});function closeCart(){dialog.close()}dialog.addEventListener('close',()=>{document.body.style.overflow=''});dialog.addEventListener('click',e=>{if(e.target.closest('[data-close]'))closeCart();const remove=e.target.closest('[data-remove]');if(remove){const index=Number(remove.dataset.remove);cart.splice(index,1);resetCheckout();renderCart();const next=dialog.querySelector(`[data-remove="${Math.min(index,cart.length-1)}"]`)||dialog.querySelector('[data-close]');next?.focus()}if(e.target===dialog&&e.clientX<dialog.getBoundingClientRect().left)closeCart()});
$('#checkout-button').addEventListener('click',()=>{$('#checkout').hidden=false;$('#checkout input').focus();$('#checkout').scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'})});
document.querySelectorAll('[name=payment]').forEach(input=>input.addEventListener('change',()=>{const manual=input.value==='manual';$('#payment-explanation').textContent=manual?'Dans la boutique finale, les coordonnées CCP seront affichées. Tu transmettras ton justificatif pour une vérification manuelle. Ce virement ne passe pas par Chargily.':'Dans la boutique finale, tu seras redirigé vers Chargily pour payer par carte CIB ou Edahabia.';$('#confirm-demo').textContent=manual?'Simuler le virement manuel':'Simuler le paiement par carte';$('#confirm-demo').disabled=false;$('#confirmation').textContent=''}));
$('#confirm-demo').addEventListener('click',()=>{const manual=$('[name=payment]:checked').value==='manual';$('#confirmation').textContent=manual?'Simulation terminée : une commande réelle attendrait le justificatif et la vérification du virement CCP / BaridiMob. Aucun paiement ni commande créés.':'Simulation terminée : une commande réelle ouvrirait la page Chargily pour CIB / Edahabia. Aucun paiement ni commande créés.';$('#confirm-demo').disabled=true});
$('.menu-button').addEventListener('click',()=>{const open=$('#nav').classList.toggle('open');$('.menu-button').setAttribute('aria-expanded',String(open))});$('#nav').addEventListener('click',e=>{if(e.target.closest('a')){$('#nav').classList.remove('open');$('.menu-button').setAttribute('aria-expanded','false')}});renderProducts();renderCart();
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){import('../assets/vendor/motion.js').then(({animate,stagger})=>{animate('.hero h1>span',{clipPath:['inset(0 0 100% 0)','inset(0 0 0% 0)'],y:[28,0]},{duration:1.1,delay:stagger(.12),ease:[.16,1,.3,1]});animate('.ticket',{y:[65,0],filter:['blur(6px)','blur(0px)']},{duration:1.4,delay:stagger(.14,{startDelay:.15}),ease:[.16,1,.3,1]});animate('.hero-note',{opacity:[.45,1],y:[15,0]},{duration:.8,delay:.35});}).catch(()=>{});}
